### PR TITLE
Rework update repository to getML version 1.4.0

### PR DESCRIPTION
**Pull request by Urfoex**
- Update notebooks to work with current versions of getML, featuretools, tsfresh, prophet ...
- Clean up contents of notebooks
- Add docker and compose files for easy local testing
- Add requirements with pinned versions for Python 3.8 and 3.11
- move binder to own project

### CODE REVIEW

**Review by liuzicheng1987 — APPROVED** [review]
Looks great! Thank you so much for the effort!

**Comment by srnnkls** [comment]
Thank you, this looks great.

I have some questions,but as there are so many changes and I’m on mobile I cannot comment inline, sorry.

- why have you introduced two runtimes? We have focused using 3.8 and 3.11 for testing purposes but I think we don’t need both runtimes to be public here
- you are using manylknux as the baseimage for the runtimes (3.8 & 3.11), why? I think this is a huge image and not necessary for a getml runtime

**Comment by Urfoex** [comment]
@srnnkls 
> why have you introduced two runtimes? We have focused using 3.8 and 3.11 for testing purposes but I think we don’t need both runtimes to be public here

3.8 is the minimum version, and 3.11 the current maximum. 3.11 supports a few newer libraries. And with upcoming changes, support for newer versions, we can quickly start and test them.
It is not necessary to put both. But also the files and code for both are very few.
And when we need to quickly check something, they are there and prepared. 

> you are using manylknux as the baseimage for the runtimes (3.8 & 3.11), why? I think this is a huge image and not necessary for a getml runtime

That is about 460MB. (https://quay.io/repository/pypa/manylinux2014_x86_64?tab=tags&tag=latest)
The standard Python image is about 360MB. (https://hub.docker.com/_/python/tags)

> python:<version>-slim
> 
> This image does not contain the common Debian packages contained in the default tag and only contains the minimal Debian packages needed to run python. Unless you are working in an environment where only the python image will be deployed and you have space constraints, we highly recommend using the default image of this repository.
> 
> When using this image pip install will work if a suitable built distribution is available for the Python distribution package being installed. pip install may fail when installing a Python distribution package from a source distribution. This image does not contain the Debian packages required to compile extension modules written in other languages.

There is also Jupyter-Lab, getML engne, getML monitor running inside. I would need to try, if they still work in the slim one. (A quick runs in problems with missing curl and can't apt install it… And pysimdjson fails with `error: command 'gcc' failed: No such file or directory`)
But are ~500MB really that much for just quickly checking things out?

Okay, on disk it is more like 1.56 GB.
And the build notebook images (with installed requirements and things) are 4.53 GB
(The ones build from Python-images are 3.85 GB and 4 GB - not too much different, I think.)

Because of PEP513... PEP600... , manylinux sounded like a good base.

**Comment by srnnkls** [comment]
Why the merge? I think there were some points still open.

Also, I think we agreed that a merge is carried out  only by PRs‘ owners _after approval_. Please guys, refrain from merging other’s PRs.

**Comment by alxn4** [comment]
Let's turn that last open question into an issue and sorry for pushing, but I don't see how this review of a rather small issue will be concluded in time for this Mondays demo. Having the main branch still on version 1.3.2, a commit from over a year ago, gives an impression that does not do justice to all the work we have put into this.

**Pull request merged**
